import React from "react";

function IndexGeneralTerms() {
  return (
    <div className="w-full bg-[#DFE3E2] min-h-screen pt-32 pb-16 md:pt-64">
      <div className="md:w-[80%] w-[90%] mx-auto">
        <div className="md:text-9xl text-7xl font-formula text-center font-bold">
          GENERAL TERMS
        </div>
        <div className="md:w-[80%] w-full leading-7 mx-auto font-neue opacity-80 mt-24">
          At FOURWARD, we are committed to protecting the privacy and security of our users' data. The FOURWARD website does not automatically recognize any data concerning the identity of visitors to its pages. In cases where users request information about services or products or wish to process complaints or incidents by submitting forms on FOURWARD websites, it will always be necessary to collect the relevant personal data to inform them of their request. All this data is treated with absolute confidentiality, being used for the purposes for which it has been requested, within the framework of applicable data protection laws and other relevant legal regulations.
          <br /><br />
          FOURWARD INC., a company incorporated in the United States, with an address at Delhi, India is the owner of the website and the file to which your Personal Data is incorporated, as well as responsible for the treatment of the same.
          <br /><br />
          Personal Data <br />
          FOURWARD will collect Personal Data from users through online forms, via the Internet. The Personal Data collected, depending on each case, will be, among others: name and surname, address, telephone number, email address, shipping address, etc. Users expressly and unequivocally give their consent for the Personal Data to be included in the Personal Data File with the number XXXXXXXXXXXXXXX, registered with the data protection agency.
          <br /><br />
          Responsibility <br />
          The use of cookies and remarketing. FOURWARD may use "cookies" when the User browses any of its web pages. A "cookie" can be defined as a text file that a website stores on the hard disk of your computer containing information relating to the User. Once your browser is closed, the cookie implanted on your computer's hard drive ceases to function. FOURWARD reserves the right to use its cookies to make the online services it provides to Users more effective and efficient. The advantages of accepting our cookies translate into time savings as the User will not have to check the registration process repeatedly. The additional advantage of cookies is that they allow us to track and target your interests in order to facilitate your stay on our Website. You have the ability to configure your browser to be notified on screen of the receipt of cookies and to prevent the installation of cookies on your hard drive. It is important that if you do not wish to accept the installation of cookies, do not forget to configure your browser accordingly. Even if you configure your browser to reject the acceptance of cookies, you will still be able to browse our website, the only drawback being the impossibility of participating in each and every one of the services offered. FOURWARD assumes no responsibility for cookies that third parties outside of our service may place on your computer's hard drive. Our website may use remarketing techniques. Remarketing allows our advertisements to be shown to people who have previously visited our website. Remarketing is anonymous and is not associated in any way with personal information. The use of remarketing requires the use of cookies that providers such as Google or Double Click that among other systems is managed through Google Analytics. You can use tools such as Google's ad settings system or disable cookies from a third party vendor via the Network Advertising Initiative opt-out page.
          <br /><br />
          Cookies used on the FOURWARD website. Following the guidelines of the relevant Data Protection Agency, we detail the use of cookies that this website uses in order to keep you informed. This website uses its own essential cookies: Session cookies, to guarantee the correct functioning of the pages and to combat spam. This website uses third-party cookies: Google Analytics: Stores cookies to compile statistics on web traffic and the volume of visits. By using this website you agree to the processing of information about you by Google. The exercise of any right in this regard must be communicated directly to Google. Social networks or video platforms: Social networks such as Facebook or Twitter use their own cookies so that you can click on their buttons such as Like or Share. Also, YouTube video players use cookies for their operation. Advertising Cookies: Google Remarketing to personalize the advertising experience.
          <br /><br />
          Information about advertising cookies. We place advertising cookies that will be installed on your computer. Advertising cookies allow us to understand your interests. The techniques used by our partners do not collect personal information such as name, email address, or telephone number.
          <br /><br />
          Deactivation or deletion of cookies. You may at any time exercise your right to deactivate or delete cookies from this website. This action is carried out differently depending on the browser you are using. Most browsers that exist usually indicate how to configure the browser to not accept cookies, to notify you each time you receive a new cookie, as well as to disable cookies completely from your browser. To control how you want the information collected to be used, you can configure your computer's browser in the way you prefer. You should be aware that in the event that cookies are disabled, the quality of the website may decrease or it may be more difficult to identify you. You can find information on the different aspects of the different browsers through these links: Chrome Support Google.com, Explorer Windows Microsoft.com, Firefox Support Mozilla.org, Safari Support Apple.com. You can also visit Network Advertising to configure and disable advertising functions.
          <br /><br />
          Additional notes. Neither this website nor its legal representatives are responsible for the content or the veracity of the privacy policies of the third parties mentioned in the cookie policy, and browsers are tools responsible for storing cookies and from them you can directly exercise the right to delete or disable cookies. Neither this website nor its legal representatives can guarantee the correct or incorrect handling of cookies by the aforementioned browsers. In some cases, it is necessary to install cookies so that the browser does not forget your decision not to accept them. In the case of Google Analytics cookies, Google stores cookies on servers located outside Spain, pledging not to share it with third parties, except in cases where necessary for the operation of the system or when the law requires it to do so. Google, as indicated, does not store IP addresses. Google Inc. is a signatory to the Safe Harbour Agreement, which guarantees that all data transferred will be treated with a level of protection in accordance with European regulations. Detailed information on this can be found at this link. If you would like information on how Google uses cookies, you can see it by clicking on this link.
          <br /><br />
          Links. This Website includes hyperlinks ("links") that allow you to move to other pages or Websites. FOURWARD accepts no responsibility whatsoever for the Data Protection Policies that may be adopted therein, and Users are advised to inform themselves of the content of the same. In any case, Users are fully aware that this Privacy Policy applies solely and exclusively to the information contained on this FOURWARD Website.
          <br /><br />
          Rights of access, rectification, cancellation, and opposition. Those individuals who have provided their data to FOURWARD may contact the latter, as the party responsible for the Personal Data File, in order to exercise their rights of access, cancellation, rectification, and opposition with respect to the data included in the Personal Data File. Given the very personal nature of these rights, it will be necessary for the affected party to prove their identity to FOURWARD. FOURWARD reserves the right to adopt the appropriate measures in order to verify their identity. The rights of access, rectification, cancellation, and opposition may be exercised in accordance with the provisions of current legislation. The User must send a written communication addressed to FOURWARD's Customer Service Department at Delhi, India.
          <br /><br />
          Upon receipt of your request, FOURWARD will notify you of its decision within the time limits set out in the applicable legislation at any given time.
          <br /><br />
          Change of Regulations FOURWARD reserves the right to modify this Privacy Policy in order to adapt it to new legislative or jurisprudential developments, as well as to those that may derive from existing standard codes on the subject or for strategic and/or corporate reasons. Any doubts, questions, or comments you may have regarding this Privacy Policy should be addressed to FOURWARD at Delhi, India without prejudice to the right to request the necessary consent of the data subjects to carry out the required processing when such consent is not considered to have been granted in accordance with the terms of this Privacy Policy.
          <br /><br />
          ADDRESS Delhi, India
          <br /><br />
          2024 © Fourward. All rights reserved.
        </div>
      </div>
    </div>
  );
}

export default IndexGeneralTerms;
